### ISSUE TITLE
BB commands don't get the correct environment from the config

### ISSUE THREAD

**Issue by vulder** [PolyJIT/benchbuild#413]
We use this env config inside the container, however, the PATH is not correctly injected into the benchbuild.util.cmd s. Further checking showed that the env values cannot be loaded from the config as usual.

```
BB_ENV={LD_LIBRARY_PATH: [/varats_root/libs], PATH [/varats_root/tools/VaRA/bin]}
```

Printing the BB config env shows this result:
```
print(bb_cfg()["env"].value)
{'default': {}, 'desc': "The environment benchbuild's commands should operate in.", 'value': {}}
```

**Comment by simbuerg** [comment]
The initial definition of ``CFG['env'] = {'default': {}, 'desc': '...'}`` triggers this bug, because it fails validation and is converted into a leaf node in the configuration.

The problem goes away when there is a config file with an ``env`` entry present. This way we load a configuration object from the file (a correct one) and load the value for it from the environment.
